/**
 * Created by karnil on 22.04.17.
 */
var _$resManifest = {
  img: [
	{ name:"jet-man", src:"img/jet-man.png"},
	{ name:"gun-man", src:"img/gun-man.png"},
	{ name:"dig-man", src:"img/dig-man.png"},
	{ name:"dig-man.2", src:"img/dig-man.2.png"},
	{ name:"shot-1", src:"img/shot-1.png"},
	{ name:"shot-2", src:"img/shot-2.png"},
	{ name:"particle", src:"img/particle.png"},
	{ name:"particle-red", src:"img/particle-red.png"},
	{ name:"particle-green", src:"img/particle-green.png"},
	{ name:"particle-blue", src:"img/particle-blue.png"},
	{ name:"particle-cyan", src:"img/particle-cyan.png"},
	{ name:"particle-yellow", src:"img/particle-yellow.png"},
	{ name:"particle-white", src:"img/particle-white.png"},
	{ name:"particle-black", src:"img/particle-black.png"},
	// tiles
	{ name:"dirt-grass-mono", src: "img/tile/dirt-grass-mono.png"},
	{ name:"grass-2", src:"img/tile/grass-2.png"},
	{ name:"grass-mono", src:"img/tile/grass-mono.png"},
	{ name:"grass", src:"img/tile/grass.png"},
	{ name:"grassy-sand-mono", src:"img/tile/grassy-sand-mono.png"},
	{ name:"grassy-snow-mono", src:"img/tile/grassy-snow-mono.png"},
	{ name:"grassy-soil-mono", src:"img/tile/grassy-soil-mono.png"},
	{ name:"grassy-soil-2-mono", src:"img/tile/grassy-soil-2-mono.png"},
	{ name:"ice-mono", src:"img/tile/ice-mono.png"},
	{ name:"sand-mono", src:"img/tile/sand-mono.png"},
	{ name:"snow-mono", src:"img/tile/snow-mono.png"},
	{ name:"soil-1.mold", src:"img/tile/soil-1.mold.png"},
	{ name:"soil-1", src:"img/tile/soil-1.png"},
	{ name:"soil-cybermold-mono", src:"img/tile/soil-cybermold-mono.png"},
	{ name:"soil-grass-mono", src:"img/tile/soil-grass-mono.png"},
	{ name:"soil-mono", src:"img/tile/soil-mono.png"},
	{ name:"soil-wired", src:"img/tile/soil-wired.png"},
	{ name:"stone-1", src:"img/tile/stone-1.png"},
	{ name:"stone-2", src:"img/tile/stone-2.png"},
	{ name:"stone-3.cybermold", src:"img/tile/stone-3.cybermold.png"},
	{ name:"stone-3.mold", src:"img/tile/stone-3.mold.png"},
	{ name:"stone-3", src:"img/tile/stone-3.png"},
	{ name:"door-1", src:"img/tile/door-1.png"},
	{ name:"door-2", src:"img/tile/door-2.png"},
	{ name:"door-3", src:"img/tile/door-3.png"},
	{ name:"door-4", src:"img/tile/door-4.png"},
	{ name:"door-5", src:"img/tile/door-5.png"},
  ],
  sfx: [
	{ name:"explosion-1", src:"sfx/explosion-1.wav" },
	{ name:"explosion-2", src:"sfx/explosion-2.wav" },
	{ name:"explosion-3", src:"sfx/explosion-3.wav" },
	{ name:"hit-1", src:"sfx/hit-1.wav" },
	{ name:"laser-1", src:"sfx/laser-1.wav" },
	{ name:"laser-2", src:"sfx/laser-2.wav" },
	{ name:"pickup-1", src:"sfx/pickup-1.wav" },
	{ name:"powerup-1", src:"sfx/powerup-1.wav" },
	{ name:"robot-1", src:"sfx/robot-1.wav" },
	{ name:"select-1", src:"sfx/select-1.wav" },
	{ name:"refill", src:"sfx/pickup-1.wav" },
  ],
};
